export const CV_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "personalInfo",
    "workExperience",
    "education",
    "skills",
    "projects",
    "certifications",
    "languages",
    "targetLanguage",
  ],
  properties: {
    personalInfo: {
      type: "object",
      additionalProperties: false,
      required: [
        "fullName",
        "title",
        "email",
        "phone",
        "location",
        "linkedinUrl",
        "githubUrl",
        "portfolioUrl",
        "summary",
      ],
      properties: {
        fullName: { type: "string" },
        title: { type: "string" },
        email: { type: "string" },
        phone: { type: "string" },
        location: { type: "string" },
        linkedinUrl: { type: "string" },
        githubUrl: { type: "string" },
        portfolioUrl: { type: "string" },
        summary: { type: "string" },
      },
    },
    workExperience: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "company",
          "position",
          "startDate",
          "endDate",
          "current",
          "location",
          "highlights",
        ],
        properties: {
          id: { type: "string" },
          company: { type: "string" },
          position: { type: "string" },
          startDate: { type: "string" },
          endDate: { type: "string" },
          current: { type: "boolean" },
          location: { type: "string" },
          highlights: { type: "array", items: { type: "string" } },
        },
      },
    },
    education: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "institution",
          "degree",
          "fieldOfStudy",
          "startDate",
          "endDate",
        ],
        properties: {
          id: { type: "string" },
          institution: { type: "string" },
          degree: { type: "string" },
          fieldOfStudy: { type: "string" },
          startDate: { type: "string" },
          endDate: { type: "string" },
        },
      },
    },
    skills: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["category", "items"],
        properties: {
          category: { type: "string" },
          items: { type: "array", items: { type: "string" } },
        },
      },
    },
    projects: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["id", "name", "description", "link", "technologies"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          description: { type: "string" },
          link: { type: "string" },
          technologies: { type: "array", items: { type: "string" } },
        },
      },
    },
    certifications: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "issuer", "date"],
        properties: {
          name: { type: "string" },
          issuer: { type: "string" },
          date: { type: "string" },
        },
      },
    },
    languages: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["language", "proficiency"],
        properties: {
          language: { type: "string" },
          proficiency: { type: "string" },
        },
      },
    },
    targetLanguage: { type: "string", enum: ["TR", "EN"] },
  },
} as const;
